{% set name = "word-forms" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/word_forms-{{ version }}.tar.gz
  sha256: 24df11f8db1a1305fa386689a080cfcd2e14458c4f31dde262c7938a45b87f74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - inflect >=4.1.0
    - nltk >=3.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - word_forms

about:
  home: https://github.com/gutfeeling/word_forms
  summary: Generate all possible forms of an English word.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
